# ASP.NET Core (.NET Framework)



# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  allureVersion: '2.14.0'  

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

  
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*\Debug\net7.0\newplaywright*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'   

- powershell: |
      $allureVersion = "2.14.0"  
      $downloadUrl = "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$allureVersion/allure-commandline-$allureVersion.zip"
      $downloadPath = "$(Agent.BuildDirectory)\allure"

      New-Item -ItemType Directory -Path $downloadPath -Force
      Invoke-WebRequest -Uri $downloadUrl -OutFile "$downloadPath\allure.zip"
      Expand-Archive -Path "$downloadPath\allure.zip" -DestinationPath $downloadPath

      $allureExecutable = "$downloadPath\allure\bin\allure.bat"
      
     
      # Generate Allure report
      
      # Publish Allure report as an artifact
      Publish-PipelineArtifact -Path "$(Agent.BuildDirectory)\allure-report" -Name "Allure-Report"