 # ASP.NET Core (.NET Framework)



# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  allureVersion: '2.14.0'  

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- script: |
    dotnet build $(solution) --configuration $(buildConfiguration)
     dotnet publish newplaywright.csproj --configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)/publish
  displayName: 'Build and Publish .NET Core App'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
    DOTNET_NOLOGO: 'true'
- script: |
   
    curl -o allure.zip -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$(allureVersion)/allure-commandline-$(allureVersion).zip
    unzip allure.zip -d $(Agent.ToolsDirectory)/allure
    echo 'export PATH=$PATH:$(Agent.ToolsDirectory)/allure/allure-$(allureVersion)_bin' >> $(Agent.ToolsDirectory)/env.sh
    source $(Agent.ToolsDirectory)/env.sh
  displayName: 'Download and Configure Allure CLI'
  env:
    allureVersion: '$(allureVersion)'

- task: CmdLine@2
  inputs:
    script: 'dotnet test'
- script: |
      "$(Agent.ToolsDirectory)\allure\allure-2.14.0\bin\allure" generate ./\bin\Debug\net7.0\allure-report --clean -o ./\bin\Debug\net7.0\allure-report