 # ASP.NET Core (.NET Framework)



# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  allureVersion: '2.14.0'  

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*\Debug\net7.0\newplaywright*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'   
   
    
- powershell: |
    
      Invoke-WebRequest -Uri https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip -OutFile allure.zip
      
      # Expand the ZIP
      Expand-Archive -Path allure.zip -DestinationPath $(Agent.ToolsDirectory)\allure

      # Add the Allure CLI to PATH
      $env:PATH += ";$(Agent.ToolsDirectory)\allure\allure-2.14.0\bin"   

- powershell: |
    
    #dotnet test newplaywright.sln
    # allure generate .$(System.DefaultWorkingDirectory)bin\Debug\net7.0 --clean -o ./allure-report
    &  "$(Agent.ToolsDirectory)\allure\allure-2.14.0\bin\allure.bat" generate ./\bin\Debug\net7.0\allure-report --clean -o ./\bin\Debug\net7.0\allure-report
   #  &  "$(Agent.ToolsDirectory)\allure\allure-2.14.0\bin\allure.bat" open ./allure-report
  displayName: 'Run Tests and Generate Allure Report'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(System.DefaultWorkingDirectory)/allure-report
    artifactName: allure-report
    publishLocation: Container
